### ISSUE TITLE
Does this require widget? 

### ISSUE THREAD

**Issue by gifthubbro** [senlin/so-related-posts#1]
Or can you use code only?

**Comment by senlin** [comment]
not sure what you mean exactly, care to elaborate?

**Comment by gifthubbro** [comment]
Nevermind, it doesnt. but, when i click on the blue + button under the post, nothing happens, would you know what im doing wrong?

**Comment by senlin** [comment]
The reason nothing happens is a [bug in Meta Box 4.5.1](https://github.com/rilwis/meta-box/issues/588) that has been reported and already has been fixed now too. If you update the Meta Box plugin to the version that was released a few hours ago ([4.5.2](https://wordpress.org/plugins/meta-box/)) you will see that it works again :)

Apologies for any inconvenience this might have caused you.
