### ISSUE TITLE
Pages support

### ISSUE THREAD

**Issue by gifthubbro** [senlin/so-related-posts#2]
If this had support for pages as well as posts i'd give it 5 stars

**Comment by senlin** [comment]
You can add "pages" to the array on [line 24 of inc/functions.php](https://github.com/senlin/so-related-posts/blob/master/inc/functions.php#L24) if you want: `array( 'post', 'page' ),`

> If this had support for pages as well as posts i'd give it 5 stars

You can leave your rating on the [WP.org Repo](https://wordpress.org/support/view/plugin-reviews/so-related-posts?rate=5#postform) :)
