### ISSUE TITLE
Can't Get Related Posts To Show On page With your Plugin

### ISSUE THREAD

**Issue by bmsj33** [senlin/so-related-posts#5]
Hello,
I just started using the Elementor Pro page builder with Generate Press Pro theme. I built a new blog page from scratch but the SO Related posts don't show up anymore on the page. I have the box checked with the related posts I want to show via the wordpress editor but I'm not sure why they don't show. I would like the image plus the title of the posts to show under my post. Any ideas as to what to do next?

**Comment by senlin** [comment]
Please see [this commit](https://github.com/senlin/so-related-posts/commit/c9f72739fb26b1ae454f0c28254355746f25dabd)

Probably best to look for another plugin my friend.
